/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package typinggame;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Federico
 */
public class StartPage extends javax.swing.JFrame implements KeyListener, Runnable {


    /**
     * Creates new form StartPage
     */
    String text;
    static Thread t;

    public StartPage() {
        initComponents();
        timerLabel.setText("0.00");
        textPane.setEditable(false);
        fakeMain();
    }

    public void fakeMain() {

        RandomInsultAPI.initialize();
        SpeakerThread.initialize();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("angry.png")));
        text = RandomTextApi.getText();
        textPane.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        timerLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        sottotitoli = new javax.swing.JLabel();
        dashboardButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textPane = new javax.swing.JTextPane(doc);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Angry Typing Game");

        jLabel1.setText("timer:");

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        sottotitoli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sottotitoli.setText("  ");

        dashboardButton.setText("dashboard");
        dashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButtonActionPerformed(evt);
            }
        });

        textPane.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jScrollPane2.setViewportView(textPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(sottotitoli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(startButton)
                            .addComponent(dashboardButton))
                        .addGap(0, 541, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(timerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startButton)
                .addGap(18, 18, 18)
                .addComponent(dashboardButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(sottotitoli)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if (vittoria) {
            vittoria = false;
            timer = 0;
            StyleConstants.setBackground(set, Color.white);
            StyleConstants.setForeground(set, Color.black);
            doc.setCharacterAttributes(0, text.length(), set, true);
            count = 0;
        }

        if (!vittoria) {
            textPane.requestFocus();
            startButton.setEnabled(false);

            t = new Thread(this);
            t.start();

        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        ApiPortal apiPortal = new ApiPortal();
        apiPortal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dashboardButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JLabel sottotitoli;
    private javax.swing.JButton startButton;
    private javax.swing.JTextPane textPane;
    private javax.swing.JLabel timerLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    StyledDocument doc = new DefaultStyledDocument();
    SimpleAttributeSet set = new SimpleAttributeSet();
    private int count = 0;
    public static double timer = 0;
    private boolean vittoria = false;

    @Override
    public void keyPressed(KeyEvent e)  {
        //System.out.println(e.getKeyChar());
        if (e.getKeyCode() != KeyEvent.VK_SHIFT) {

            if (e.getKeyChar() == textPane.getText().charAt(count)) {
                //System.out.println("giusto");

                StyleConstants.setBackground(set, Color.green);
                StyleConstants.setForeground(set, Color.black);
                doc.setCharacterAttributes(count, 1, set, true);
                count++;

            } else {
                StyleConstants.setBackground(set, Color.red);
                StyleConstants.setForeground(set, Color.white);
                doc.setCharacterAttributes(count, 1, set, true);

                SpeakerThread.speak(RandomInsultAPI.getInsult());           //dice la stringa immessa

                //System.out.println("sbagliato");
            }

            if (count == text.length()) {
                System.out.println("vittoria");
                vittoria = true;
                startButton.setEnabled(true);
                textPane.removeKeyListener(this);
                t.stop();

            }
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }

    private static DecimalFormat df2 = new DecimalFormat("#.##");

    @Override
    public void run() {
        textPane.addKeyListener(this);
        System.out.println("entrato");
        while (true) {
            timer += 0.01;
            try {
                Thread.sleep(10);
            } catch (InterruptedException ex) {
                Logger.getLogger(TypingGame.class.getName()).log(Level.SEVERE, null, ex);
            }
            if( SpeakerThread.threads.size() > 0 )
                sottotitoli.setText(SpeakerThread.threads.get(SpeakerThread.threads.size()-1).currentText);
            else
                sottotitoli.setText("");
            timerLabel.setText(df2.format(timer));
        }
    }
}
